import Header from "@/components/Header";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import Sidebar from "@/components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="max-w-[1024px] mx-auto pl-[20px] pr-[20px]">
              <div className="pb-[15px]">
                <Header />
              </div>
              <div className="grid grid-cols-1 gap-4 lg:grid-cols-12">
                <div className="hidden lg:block lg:col-span-3">
                  <Sidebar />
                </div>
                <div className="flex flex-col items-center min-h-screen lg:col-span-9">
                  {children}
                </div>
              </div>
            </div>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
